// brewingcodes/webapi-session3_08-Aug-2020/Source/college-web/src/app/components/top-navbar/top-navbar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-top-navbar',
  templateUrl: './top-navbar.component.html',
  styleUrls: ['./top-navbar.component.css']
})
export class TopNavbarComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<nav class="navbar navbar-expand-md navbar-dark bg-primary">
  <div class="container">
    <a routerLink="/" class="navbar-brand">College</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a routerLink="/professors" class="nav-link">Professors</a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a routerLink="/register" class="nav-link">Register</a>
        </li>
        <li class="nav-item">
          <a routerLink="/login" class="nav-link">Login</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

// AzConf/Source/4webapp-reactjs/src/components/layout/TopNavbar.js
import React from 'react';
import PropTypes from 'prop-types';
import { Link } from 'react-router-dom';

const TopNavbar = ({ icon, title }) => {
  return (
    <nav className="navbar navbar-expand-md navbar-dark top-navbar-color">
      <div className="container">
        <Link to="/dashboard" className="navbar-brand"><i className="fa fa-university" aria-hidden="true"></i> {title}</Link>
        <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain">
          <span className="navbar-toggler-icon"></span>
        </button>
        <div className="collapse navbar-collapse" id="navbarMain">
          <ul className="navbar-nav mr-auto">
            <li className="nav-item">
              <Link to='/professors'>Professors</Link>
            </li>
            <li className="nav-item">
              <Link to='/about'>About</Link>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  );
};

TopNavbar.defaultProps = {
  title: 'Book Stores',
  icon: 'fa fa-book'
};

TopNavbar.propTypes = {
  title: PropTypes.string.isRequired,
  icon: PropTypes.string.isRequired
};

export default TopNavbar;
